-- CREATE TABLE todos (
--     id INT AUTO_INCREMENT PRIMARY KEY,
--     title VARCHAR(255) NOT NULL,
--     description TEXT,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );
-- CREATE TABLE
--     todos (
--         id INT AUTO_INCREMENT PRIMARY KEY,
--         task VARCHAR(255) NOT NULL,
--         description TEXT,
--         done BOOLEAN DEFAULT FALSE,
--         created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--         ended_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
--     );